# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='api_Movie_code',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imgUrl',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
    ]
